name: Hello world!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say Hello
        run: | 
          echo "Hello world!"
  date_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Now it is
        run: | 
          date
  directory_content_job:
    runs-on:
    steps:
      - name: Directory content
        run: |
          ls -l
  
